# Generated by Django 4.1.13 on 2023-12-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pedidos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pedido",
            name="coste_total",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
