# Generated by Django 4.1.13 on 2023-12-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='coste_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('EP', 'En preparación'), ('EC', 'En camino'), ('RB', 'Recibido')], default='EP', max_length=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='num_referencia',
            field=models.BigIntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
