# Generated by Django 4.1.13 on 2023-12-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_pedido_coste_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('GE', 'General'), ('EX', 'Express'), ('RT', 'Recogida en Tienda')], default='EP', max_length=14),
        ),
        migrations.AddField(
            model_name='pedido',
            name='num_referencia',
            field=models.BigIntegerField(default=0, unique=True),
        ),
    ]
