# Generated by Django 4.1.13 on 2023-12-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_estado_pedido_pedido_num_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('EP', 'En preparación'), ('EC', 'En camino'), ('RB', 'Recibido')], default='EP', max_length=14),
        ),
    ]
